### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [kravietz/nist-sts#2]
Hi! what would be the license for this repo? I could not find much.

Is this the same as I guess as at http://csrc.nist.gov/groups/ST/toolkit/rng/documentation_software.html ?
e.g.

> Software disclaimer: "This software was developed at the National Institute of Standards and Technology by employees of the Federal Government in the course of their official duties. Pursuant to title 17 Section 105 of the United States Code this software is not subject to copyright protection and is in the public domain. The NIST Statistical Test Suite is an experimental system. NIST assumes no responsibility whatsoever for its use by other parties, and makes no guarantees, expressed or implied, about its quality, reliability, or any other characteristic. We would appreciate acknowledgment if the software is used."

**Comment by kravietz** [comment]
Created a new LICENSE file
