### ISSUE TITLE
Getting this error "MAIN: Could not open freq file: <experiments/AlgorithmTesting/freq.txt>"

### ISSUE THREAD

**Issue by kunalbathija** [kravietz/nist-sts#4]
All previous code is running properply but I got stuck here, please reply any solution.

**Comment by kravietz** [comment]
You need to download the test NIST data package from http://csrc.nist.gov/groups/ST/toolkit/rng/documentation_software.html

**Comment by kunalbathija** [comment]
Thanks mate!!

Kunal S. Bathija
