### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by RasikaNaik** [kravietz/nist-sts#5]
I am trying to run NIST.exe file on windows command prompt for randomness testing.
i have downloaded STS 2.1.2 
when I run NIST.exe I am getting following error:
**MAIN:  Could not open freq file: <experiments/AlgorithmTesting/freq.txt>**

Can you please guide me on this???

**Comment by kravietz** [comment]
You need to download the test NIST data package from http://csrc.nist.gov/groups/ST/toolkit/rng/documentation_software.html
